package cn.tico.iot.configmanger.module.iot.services;

import cn.tico.iot.configmanger.common.base.Service;
import cn.tico.iot.configmanger.module.iot.models.Topo.Topo;
import org.nutz.dao.Dao;
import org.nutz.ioc.loader.annotation.Inject;
import org.nutz.ioc.loader.annotation.IocBean;
import org.nutz.json.Json;

@IocBean(args = {"refer:dao"})
public class TopoService extends Service<Topo> {

    public TopoService(Dao dao) {
        super(dao);
    }

    @Inject
    TagService tagService;

    public Object drawByTag(String tag) {

        return Json.fromJson(testtemp);
    }
    static  final  String testtemp = "{    " +
            "   \"code\": 0,\n" +
            "    \"msg\": \"操作成功\",\n" +
            "    \"data\": {\n" +
            "  \"nodes\": [{\n" +
            "            \"id\": \"0\",\n" +
            "            \"sno\": \"CR2160816028\",\n" +
            "            \"icon\": \"MCU.png\",\n" +
            "            \"type\": \"MCU\",\n" +
            "            \"ip\": \"196.168.0.105\",\n" +
            "            \"label\": \"宝利通MCU主\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1517.4254471398465,\n" +
            "            \"y\": -2.937462286745955\n" +
            "        }, {\n" +
            "            \"id\": \"1\",\n" +
            "            \"sno\": \"CR2161207027\",\n" +
            "            \"icon\": \"MCU.png\",\n" +
            "            \"type\": \"MCU\",\n" +
            "            \"ip\": \"196.168.0.100\",\n" +
            "            \"label\": \"宝利通MCU备\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1886.7388274035275,\n" +
            "            \"y\": -3.6301095254737348\n" +
            "        }, {\n" +
            "            \"id\": \"2\",\n" +
            "            \"sno\": \"2102350DLSDMJB001611\",\n" +
            "            \"icon\": \"switch.png\",\n" +
            "            \"type\": \"switch\",\n" +
            "            \"ip\": \"196.168.255.252\",\n" +
            "            \"label\": \"QM-Video-Core-1\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1515.9817515881382,\n" +
            "            \"y\": 87.7815222414572\n" +
            "        }, {\n" +
            "            \"id\": \"3\",\n" +
            "            \"sno\": \"2102350DLSDMJB001614\",\n" +
            "            \"icon\": \"switch.png\",\n" +
            "            \"type\": \"switch\",\n" +
            "            \"ip\": \"196.168.255.253\",\n" +
            "            \"label\": \"QM-Video-Core-2\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1885.3341795761212,\n" +
            "            \"y\": 90.65431714893549\n" +
            "        }, {\n" +
            "            \"id\": \"4\",\n" +
            "            \"sno\": \"2102359504DMK5001449\",\n" +
            "            \"icon\": \"switch.png\",\n" +
            "            \"type\": \"switch\",\n" +
            "            \"ip\": \"196.168.255.1\",\n" +
            "            \"label\": \"QM-Video-Access-1\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1129.7353943748992,\n" +
            "            \"y\": 201.21337958269362\n" +
            "        }, {\n" +
            "            \"id\": \"5\",\n" +
            "            \"sno\": \"2102359504DMK5001438\",\n" +
            "            \"icon\": \"switch.png\",\n" +
            "            \"type\": \"switch\",\n" +
            "            \"ip\": \"196.168.255.2\",\n" +
            "            \"label\": \"QM-Video-Access-2\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1595.5892470059543,\n" +
            "            \"y\": 206.064770524611\n" +
            "        }, {\n" +
            "            \"id\": \"6\",\n" +
            "            \"sno\": \"2102359504DMK5001523\",\n" +
            "            \"icon\": \"switch.png\",\n" +
            "            \"type\": \"switch\",\n" +
            "            \"ip\": \"196.168.255.3\",\n" +
            "            \"label\": \"QM-Video-Access-3\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1933.2752703364556,\n" +
            "            \"y\": 205.17126651097598\n" +
            "        }, {\n" +
            "            \"id\": \"7\",\n" +
            "            \"sno\": \"2102359504DMK7002171\",\n" +
            "            \"icon\": \"switch.png\",\n" +
            "            \"type\": \"switch\",\n" +
            "            \"ip\": \"196.168.255.4\",\n" +
            "            \"label\": \"QM-Video-Access-4\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2101.1449052995013,\n" +
            "            \"y\": 203.50555808809065\n" +
            "        }, {\n" +
            "            \"id\": \"8\",\n" +
            "            \"sno\": \"FD1616313048D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.31\",\n" +
            "            \"label\": \"721会议终端主用行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1191.688157001477,\n" +
            "            \"y\": 501.87644479070275\n" +
            "        }, {\n" +
            "            \"id\": \"9\",\n" +
            "            \"sno\": \"FD152430C15BD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.30\",\n" +
            "            \"label\": \"721会议终端备用行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1021.1753754001984,\n" +
            "            \"y\": 532.9373504038234\n" +
            "        }, {\n" +
            "            \"id\": \"11\",\n" +
            "            \"sno\": \"82150542D281CG\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.66\",\n" +
            "            \"label\": \"城区公司行政-7000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1023.1022867650416,\n" +
            "            \"y\": 482.43262831695813\n" +
            "        }, {\n" +
            "            \"id\": \"12\",\n" +
            "            \"sno\": \"FD161630CFB0D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.82\",\n" +
            "            \"label\": \"朝阳公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1030.5560625716764,\n" +
            "            \"y\": 286.8233961754889\n" +
            "        }, {\n" +
            "            \"id\": \"13\",\n" +
            "            \"sno\": \"FD161330CDB2D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.146\",\n" +
            "            \"label\": \"海淀公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1025.5484289155988,\n" +
            "            \"y\": 382.7693225461587\n" +
            "        }, {\n" +
            "            \"id\": \"14\",\n" +
            "            \"sno\": \"82151943A1B0CN\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.18\",\n" +
            "            \"label\": \"丰台公司行政-7000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1024.4762657950048,\n" +
            "            \"y\": 431.00115660094207\n" +
            "        }, {\n" +
            "            \"id\": \"15\",\n" +
            "            \"sno\": \"FD161631307DD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.130\",\n" +
            "            \"label\": \"石景山公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1341.0156076135372,\n" +
            "            \"y\": 524.4935345735533\n" +
            "        }, {\n" +
            "            \"id\": \"16\",\n" +
            "            \"sno\": \"FD161330CE90D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.146\",\n" +
            "            \"label\": \"亦庄公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1507.9966680703142,\n" +
            "            \"y\": 430.3472135902131\n" +
            "        }, {\n" +
            "            \"id\": \"17\",\n" +
            "            \"sno\": \"FD1635314358D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.82\",\n" +
            "            \"label\": \"通州公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1181.7341308911023,\n" +
            "            \"y\": 557.1059325894942\n" +
            "        }, {\n" +
            "            \"id\": \"18\",\n" +
            "            \"sno\": \"FD1818319F36D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.34\",\n" +
            "            \"label\": \"昌平公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1191.4929149036566,\n" +
            "            \"y\": 446.87703653535544\n" +
            "        }, {\n" +
            "            \"id\": \"19\",\n" +
            "            \"sno\": \"FD161330CD8AD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.51\",\n" +
            "            \"label\": \"门头沟公司双流(行政)-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1193.6673618098764,\n" +
            "            \"y\": 399.0903450540166\n" +
            "        }, {\n" +
            "            \"id\": \"20\",\n" +
            "            \"sno\": \"FD1616313028D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.162\",\n" +
            "            \"label\": \"房山公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1033.2111220517565,\n" +
            "            \"y\": 234.09898795609678\n" +
            "        }, {\n" +
            "            \"id\": \"21\",\n" +
            "            \"sno\": \"FD161630CFD7D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.50\",\n" +
            "            \"label\": \"大兴公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2218.138878643964,\n" +
            "            \"y\": 276.89471074786627\n" +
            "        }, {\n" +
            "            \"id\": \"22\",\n" +
            "            \"sno\": \"8210320B2CB5B9\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.178\",\n" +
            "            \"label\": \"平谷公司行政8000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1028.2775061960083,\n" +
            "            \"y\": 335.1885488542384\n" +
            "        }, {\n" +
            "            \"id\": \"23\",\n" +
            "            \"sno\": \"FD1616313084D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.34\",\n" +
            "            \"label\": \"怀柔公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1341.9832381207027,\n" +
            "            \"y\": 235.02270696418714\n" +
            "        }, {\n" +
            "            \"id\": \"24\",\n" +
            "            \"sno\": \"FD1722315AD1D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.2\",\n" +
            "            \"label\": \"密云公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1343.4698633042638,\n" +
            "            \"y\": 474.2649832768286\n" +
            "        }, {\n" +
            "            \"id\": \"25\",\n" +
            "            \"sno\": \"FD1616313003D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.66\",\n" +
            "            \"label\": \"顺义公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2218.400424500463,\n" +
            "            \"y\": 322.84687998341377\n" +
            "        }, {\n" +
            "            \"id\": \"26\",\n" +
            "            \"sno\": \"FD161631302BD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.97\",\n" +
            "            \"label\": \"延庆公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1343.4858447993547,\n" +
            "            \"y\": 426.9063605229386\n" +
            "        }, {\n" +
            "            \"id\": \"27\",\n" +
            "            \"sno\": \"FD161630CFECD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.66\",\n" +
            "            \"label\": \"经研院行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1510.5567963525975,\n" +
            "            \"y\": 380.8576151669114\n" +
            "        }, {\n" +
            "            \"id\": \"28\",\n" +
            "            \"sno\": \"FD1722315AD1D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.2\",\n" +
            "            \"label\": \"电科院行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1511.1560908023905,\n" +
            "            \"y\": 332.80048586914086\n" +
            "        }, {\n" +
            "            \"id\": \"29\",\n" +
            "            \"sno\": \"821334411353CN\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.34\",\n" +
            "            \"label\": \"工程公司行政-hdx8000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1511.7778381045384,\n" +
            "            \"y\": 285.0412182033823\n" +
            "        }, {\n" +
            "            \"id\": \"30\",\n" +
            "            \"sno\": \"8212370F59DDCN\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.2\",\n" +
            "            \"label\": \"检修公司行政-hdx7000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1342.1107475255842,\n" +
            "            \"y\": 378.8953026623259\n" +
            "        }, {\n" +
            "            \"id\": \"31\",\n" +
            "            \"sno\": \"FD183531B12CD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.50\",\n" +
            "            \"label\": \"信通公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1340.9087825188456,\n" +
            "            \"y\": 331.437393825923\n" +
            "        }, {\n" +
            "            \"id\": \"32\",\n" +
            "            \"sno\": \"FD161631300BD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.130\",\n" +
            "            \"label\": \"培训中心行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2220.087423172927,\n" +
            "            \"y\": 370.8832629223677\n" +
            "        }, {\n" +
            "            \"id\": \"33\",\n" +
            "            \"sno\": \"FD161630CFA5D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.5.178\",\n" +
            "            \"label\": \"物资公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2221.6684857516702,\n" +
            "            \"y\": 422.40129018969145\n" +
            "        }, {\n" +
            "            \"id\": \"34\",\n" +
            "            \"sno\": \"FD1616313016D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.194\",\n" +
            "            \"label\": \"客服中心行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1851.0183824223625,\n" +
            "            \"y\": 280.5852792512941\n" +
            "        }, {\n" +
            "            \"id\": \"35\",\n" +
            "            \"sno\": \"FD161630CFE7D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.210\",\n" +
            "            \"label\": \"电动车公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1850.3668899842537,\n" +
            "            \"y\": 333.68681500943825\n" +
            "        }, {\n" +
            "            \"id\": \"36\",\n" +
            "            \"sno\": \"821338409C1FCG\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.98\",\n" +
            "            \"label\": \"承发包公司行政-hdx8000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1679.5148511945984,\n" +
            "            \"y\": 432.144196001179\n" +
            "        }, {\n" +
            "            \"id\": \"37\",\n" +
            "            \"sno\": \"FD154430C4CBD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.226\",\n" +
            "            \"label\": \"电缆分公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1338.4638103712314,\n" +
            "            \"y\": 285.63468294709014\n" +
            "        }, {\n" +
            "            \"id\": \"38\",\n" +
            "            \"sno\": \"FD161630CF56D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.18\",\n" +
            "            \"label\": \"照明中心行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1678.9458588723396,\n" +
            "            \"y\": 383.56800938887875\n" +
            "        }, {\n" +
            "            \"id\": \"39\",\n" +
            "            \"sno\": \"FD161630CF3BD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.162\",\n" +
            "            \"label\": \"华商伟业行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2222.2570069189283,\n" +
            "            \"y\": 481.8146248064276\n" +
            "        }, {\n" +
            "            \"id\": \"40\",\n" +
            "            \"sno\": \"FD150330B592D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.114\",\n" +
            "            \"label\": \"华商远大行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1852.2184777585433,\n" +
            "            \"y\": 384.7386926821488\n" +
            "        }, {\n" +
            "            \"id\": \"41\",\n" +
            "            \"sno\": \"FD1616313057D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.5.34\",\n" +
            "            \"label\": \"华商三优行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1851.5669853204338,\n" +
            "            \"y\": 434.34687480315097\n" +
            "        }, {\n" +
            "            \"id\": \"42\",\n" +
            "            \"sno\": \"FD1616313001D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.226\",\n" +
            "            \"label\": \"华商能源行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2021.198257654674,\n" +
            "            \"y\": 279.0134800692459\n" +
            "        }, {\n" +
            "            \"id\": \"43\",\n" +
            "            \"sno\": \"FD161631305ED7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.5.18\",\n" +
            "            \"label\": \"华商电灯行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2020.1624543255462,\n" +
            "            \"y\": 331.89336418468383\n" +
            "        }, {\n" +
            "            \"id\": \"44\",\n" +
            "            \"sno\": \"FD161630CF1CD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.242\",\n" +
            "            \"label\": \"吉北咨询行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2020.4422429177876,\n" +
            "            \"y\": 379.8016434932983\n" +
            "        }, {\n" +
            "            \"id\": \"45\",\n" +
            "            \"sno\": \"FD161631300DD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.130\",\n" +
            "            \"label\": \"京电设计行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2019.9188541100182,\n" +
            "            \"y\": 431.3659356873673\n" +
            "        }, {\n" +
            "            \"id\": \"46\",\n" +
            "            \"sno\": \"8211170DE64FCN\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.242\",\n" +
            "            \"label\": \"银杰公司行政-7000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1678.3880929762583,\n" +
            "            \"y\": 333.05344179644305\n" +
            "        }, {\n" +
            "            \"id\": \"47\",\n" +
            "            \"sno\": \"FD162831325AD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.50\",\n" +
            "            \"label\": \"谷新公司行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1677.4116006976035,\n" +
            "            \"y\": 281.900871172663\n" +
            "        }, {\n" +
            "            \"id\": \"48\",\n" +
            "            \"sno\": \"82163143B910CN\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.98\",\n" +
            "            \"label\": \"中电联汽车行政-7000\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 1850.5563960816085,\n" +
            "            \"y\": 488.2861435792786\n" +
            "        }, {\n" +
            "            \"id\": \"49\",\n" +
            "            \"sno\": \"FD1648314584D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.17\",\n" +
            "            \"label\": \"公司巡察办行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2024.5533106889475,\n" +
            "            \"y\": 486.84244802757013\n" +
            "        }, {\n" +
            "            \"id\": \"50\",\n" +
            "            \"sno\": \"FD184631BA2BD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.114\",\n" +
            "            \"label\": \"重点工程生产办公室行政-group550\",\n" +
            "            \"description\": \"\",\n" +
            "            \"x\": 2187.3683998093147,\n" +
            "            \"y\": 537.1378343975698\n" +
            "        }, {\n" +
            "            \"id\": \"51\",\n" +
            "            \"sno\": \"FD183531ABF3D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.10\",\n" +
            "            \"label\": \"应急指挥中心1-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"52\",\n" +
            "            \"sno\": \"FD161631300CD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.20\",\n" +
            "            \"label\": \"639会议终端主用行政-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"53\",\n" +
            "            \"sno\": \"FD1616313009D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.21\",\n" +
            "            \"label\": \"639会议终端备用行政-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"54\",\n" +
            "            \"sno\": \"FD154430C863D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.40\",\n" +
            "            \"label\": \"B座二层1-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"55\",\n" +
            "            \"sno\": \"FD1616313029D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.41\",\n" +
            "            \"label\": \"B座二层2-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"56\",\n" +
            "            \"sno\": \"FD183531AFBDD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.2\",\n" +
            "            \"label\": \"19006公司总指挥部1-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"57\",\n" +
            "            \"sno\": \"FD185131BDF7D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.206\",\n" +
            "            \"label\": \"19006公司总指挥部2-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"58\",\n" +
            "            \"sno\": \"FD182031A1E8D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.0.11\",\n" +
            "            \"label\": \"应急指挥中心2-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"59\",\n" +
            "            \"sno\": \"FD154430C945D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.33\",\n" +
            "            \"label\": \"昌平公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"60\",\n" +
            "            \"sno\": \"FD183531B079D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.161\",\n" +
            "            \"label\": \"电缆分公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"61\",\n" +
            "            \"sno\": \"FD185131BD75D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.97\",\n" +
            "            \"label\": \"朝阳公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"62\",\n" +
            "            \"sno\": \"FD1628313219D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.65\",\n" +
            "            \"label\": \"大兴公司八层应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"63\",\n" +
            "            \"sno\": \"FD161330CDABD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.145\",\n" +
            "            \"label\": \"亦庄公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"64\",\n" +
            "            \"sno\": \"FD161330CE93D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.193\",\n" +
            "            \"label\": \"客服中心应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"65\",\n" +
            "            \"sno\": \"FD162831331FD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.161\",\n" +
            "            \"label\": \"房山公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"66\",\n" +
            "            \"sno\": \"FD16283131A9D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.17\",\n" +
            "            \"label\": \"丰台公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"67\",\n" +
            "            \"sno\": \"FD154430C49FD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.1\",\n" +
            "            \"label\": \"电科院应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"68\",\n" +
            "            \"sno\": \"FD16283132CFD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.17\",\n" +
            "            \"label\": \"照明中心应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"69\",\n" +
            "            \"sno\": \"FD16283131B1D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.241\",\n" +
            "            \"label\": \"检修公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"70\",\n" +
            "            \"sno\": \"FD182031A12ED7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.33\",\n" +
            "            \"label\": \"工程公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"71\",\n" +
            "            \"sno\": \"FD1812319644D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.161\",\n" +
            "            \"label\": \"华商远大应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"72\",\n" +
            "            \"sno\": \"82151242D55FCG\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.145\",\n" +
            "            \"label\": \"海淀公司应急-hdx8000\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"73\",\n" +
            "            \"sno\": \"FD162831325DD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.33\",\n" +
            "            \"label\": \"怀柔公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"74\",\n" +
            "            \"sno\": \"FD18033193C3D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.49\",\n" +
            "            \"label\": \"门头沟新会场行政（应急）-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"75\",\n" +
            "            \"sno\": \"FD1628313230D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.1\",\n" +
            "            \"label\": \"密云公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"76\",\n" +
            "            \"sno\": \"FD16283131A3D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.1.177\",\n" +
            "            \"label\": \"平谷公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"77\",\n" +
            "            \"sno\": \"FD1722315A9BD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.81\",\n" +
            "            \"label\": \"顺义公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"78\",\n" +
            "            \"sno\": \"FD1616313007D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.113\",\n" +
            "            \"label\": \"通州公司应急-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"79\",\n" +
            "            \"sno\": \"FD184631B8AAD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.68\",\n" +
            "            \"label\": \"城区公司五层-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"80\",\n" +
            "            \"sno\": \"FD191031C8D8D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.5.81\",\n" +
            "            \"label\": \"昌平19006分指挥部-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"81\",\n" +
            "            \"sno\": \"82134341259BCN\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.242\",\n" +
            "            \"label\": \"国家会议中心现场指挥部-hdx7000\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"82\",\n" +
            "            \"sno\": \"FD1628313232D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.18\",\n" +
            "            \"label\": \"芦城应急抢修中心-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"83\",\n" +
            "            \"sno\": \"FD190331C08DD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.5.114\",\n" +
            "            \"label\": \"大兴机场东-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"84\",\n" +
            "            \"sno\": \"FD1748318D83D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.242\",\n" +
            "            \"label\": \"照明中心广场指挥部-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"85\",\n" +
            "            \"sno\": \"FD182031A63DD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.6.81\",\n" +
            "            \"label\": \"广场区现场指挥部-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"86\",\n" +
            "            \"sno\": \"FD1628313200D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.178\",\n" +
            "            \"label\": \"大雁楼备-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"87\",\n" +
            "            \"sno\": \"FD16353141B6D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.146\",\n" +
            "            \"label\": \"大雁楼主-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"88\",\n" +
            "            \"sno\": \"FD1635314344D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.209\",\n" +
            "            \"label\": \"国际会都现场指挥部-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"89\",\n" +
            "            \"sno\": \"FD162831371ED7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.130\",\n" +
            "            \"label\": \"通州大会议室-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"90\",\n" +
            "            \"sno\": \"FD180331942FD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.2.193\",\n" +
            "            \"label\": \"世园会现场指挥部备-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"91\",\n" +
            "            \"sno\": \"FD17033152F6D7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.4.33\",\n" +
            "            \"label\": \"会城门-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"92\",\n" +
            "            \"sno\": \"FD1818319F6BD7\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"196.168.3.130\",\n" +
            "            \"label\": \"冬奥会西单办公室-group550\",\n" +
            "            \"description\": \"\"\n" +
            "        }, {\n" +
            "            \"id\": \"93\",\n" +
            "            \"sno\": \"T0L832T4006ZBTT0L832T4001BBT\",\n" +
            "            \"icon\": \"terminal.png\",\n" +
            "            \"type\": \"meeting_terminal\",\n" +
            "            \"ip\": \"192.168.1.200\",\n" +
            "            \"label\": \"小鸟拼接处理器\",\n" +
            "            \"description\": \"\"\n" +
            "        }],\n" +
            "        \"edges\": [{\n" +
            "            \"source\": \"0\",\n" +
            "            \"target\": \"2\",\n" +
            "            \"description\": \"宝利通MCU主:管理LAN ,QM-Video-Core-1:G0/0/8\",\n" +
            "            \"id\": \"edge-0\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"0\",\n" +
            "            \"description\": \"宝利通MCU主:信令LAN ,QM-Video-Core-1:G0/0/10\",\n" +
            "            \"id\": \"edge-0-1\"\n" +
            "        }, {\n" +
            "            \"source\": \"1\",\n" +
            "            \"target\": \"2\",\n" +
            "            \"description\": \"宝利通MCU备:管理LAN,QM-Video-Core-1:G0/0/12\",\n" +
            "            \"id\": \"edge-1\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"3\",\n" +
            "            \"description\": \"QM-Video-Core-1:G0/0/27,QM-Video-Core-2:G0/0/27\",\n" +
            "            \"id\": \"edge-2\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"2\",\n" +
            "            \"description\": \"QM-Video-Core-1:G0/0/28,QM-Video-Core-2:G0/0/28\",\n" +
            "            \"id\": \"edge-3\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"4\",\n" +
            "            \"description\": \"QM-Video-Core-1:G0/0/21,QM-Video-Access-1:G0/0/49\",\n" +
            "            \"id\": \"edge-4\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"4\",\n" +
            "            \"description\": \"QM-Video-Core-2:G0/0/21,QM-Video-Access-1:G0/0/51\",\n" +
            "            \"id\": \"edge-5\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"5\",\n" +
            "            \"description\": \"QM-Video-Core-1:G0/0/22,QM-Video-Access-2:G0/0/49\",\n" +
            "            \"id\": \"edge-6\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"5\",\n" +
            "            \"description\": \"QM-Video-Core-2:G0/0/22,QM-Video-Access-2:G0/0/51\",\n" +
            "            \"id\": \"edge-7\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"6\",\n" +
            "            \"description\": \"QM-Video-Core-1:G0/0/23,QM-Video-Access-3:G0/0/49\",\n" +
            "            \"id\": \"edge-8\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"6\",\n" +
            "            \"description\": \"QM-Video-Core-2:G0/0/23,QM-Video-Access-3:G0/0/51\",\n" +
            "            \"id\": \"edge-9\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"7\",\n" +
            "            \"description\": \"QM-Video-Core-1:G0/0/24,QM-Video-Access-4:G0/0/49\",\n" +
            "            \"id\": \"edge-10\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"7\",\n" +
            "            \"description\": \"QM-Video-Core-2:G0/0/24,QM-Video-Access-4:G0/0/51\",\n" +
            "            \"id\": \"edge-11\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"8\",\n" +
            "            \"description\": \"core-switch-1:G0/0/7,721会议终端主用行政:LAN1\",\n" +
            "            \"id\": \"edge-12\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"9\",\n" +
            "            \"description\": \"core-switch-2:G0/0/7,721会议终端备用行政:LAN1\",\n" +
            "            \"id\": \"edge-13\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"11\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/41,城区公司行政:LAN1\",\n" +
            "            \"id\": \"edge-14\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"12\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/11,朝阳公司行政:LAN1\",\n" +
            "            \"id\": \"edge-15\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"13\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/19,海淀公司行政:LAN1\",\n" +
            "            \"id\": \"edge-16\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"14\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/3,丰台公司行政:LAN1\",\n" +
            "            \"id\": \"edge-17\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"15\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/17,石景山公司行政:LAN1\",\n" +
            "            \"id\": \"edge-18\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"16\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/3,亦庄公司行政:LAN1\",\n" +
            "            \"id\": \"edge-19\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"17\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/43,通州公司行政:LAN1\",\n" +
            "            \"id\": \"edge-20\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"18\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/37,昌平公司行政:LAN1\",\n" +
            "            \"id\": \"edge-21\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"19\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/7,门头沟公司双流(行政):LAN1\",\n" +
            "            \"id\": \"edge-22\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"20\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/21,房山公司行政:LAN1\",\n" +
            "            \"id\": \"edge-23\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"21\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/23,大兴公司行政:LAN1\",\n" +
            "            \"id\": \"edge-24\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"22\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/23,平谷公司行政:LAN1\",\n" +
            "            \"id\": \"edge-25\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"23\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/5,怀柔公司行政:LAN1\",\n" +
            "            \"id\": \"edge-26\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"24\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/1,密云公司行政:LAN1\",\n" +
            "            \"id\": \"edge-27\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"25\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/25,顺义公司行政:LAN1\",\n" +
            "            \"id\": \"edge-28\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"26\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/45,延庆公司行政:LAN1\",\n" +
            "            \"id\": \"edge-29\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"27\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/25,经研院行政:LAN1\",\n" +
            "            \"id\": \"edge-30\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"28\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/17,电科院行政:LAN1\",\n" +
            "            \"id\": \"edge-31\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"29\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/21,工程公司行政:LAN1\",\n" +
            "            \"id\": \"edge-32\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"30\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/33,检修公司行政:LAN1\",\n" +
            "            \"id\": \"edge-33\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"31\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/39,信通公司行政:LAN1\",\n" +
            "            \"id\": \"edge-34\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"32\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/33,培训中心行政:LAN1\",\n" +
            "            \"id\": \"edge-35\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"33\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/7,物资公司行政:LAN1\",\n" +
            "            \"id\": \"edge-36\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"34\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/25,客服中心行政:LAN1\",\n" +
            "            \"id\": \"edge-37\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"35\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/27,电动车公司行政:LAN1\",\n" +
            "            \"id\": \"edge-38\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"36\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/29,承发包公司行政:LAN1\",\n" +
            "            \"id\": \"edge-39\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"37\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/29,电缆分公司行政:LAN1\",\n" +
            "            \"id\": \"edge-40\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"38\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/19,照明中心行政:LAN1\",\n" +
            "            \"id\": \"edge-41\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"39\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/37,华商伟业行政:LAN1\",\n" +
            "            \"id\": \"edge-42\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"40\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/21,华商远大行政:LAN1\",\n" +
            "            \"id\": \"edge-43\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"41\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/37,华商三优行政:LAN1\",\n" +
            "            \"id\": \"edge-44\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"42\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/29,华商能源行政:LAN1\",\n" +
            "            \"id\": \"edge-45\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"43\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/35,华商电灯行政:LAN1\",\n" +
            "            \"id\": \"edge-46\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"44\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/31,吉北咨询行政:LAN1\",\n" +
            "            \"id\": \"edge-47\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"45\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/17,京电设计行政:LAN1\",\n" +
            "            \"id\": \"edge-48\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"46\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/47,银杰公司行政:LAN1\",\n" +
            "            \"id\": \"edge-49\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"47\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/23,谷新公司行政:LAN1\",\n" +
            "            \"id\": \"edge-50\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"48\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/13,中电联汽车行政:LAN1\",\n" +
            "            \"id\": \"edge-51\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"49\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/33,公司巡察办行政:LAN1\",\n" +
            "            \"id\": \"edge-52\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"50\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/19,重点工程生产办公室行政:LAN1\",\n" +
            "            \"id\": \"edge-53\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"51\",\n" +
            "            \"description\": \"core-switch-1:G0/0/1,应急指挥中心1:LAN1\",\n" +
            "            \"id\": \"edge-54\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"52\",\n" +
            "            \"description\": \"core-switch-1:G0/0/5,639会议终端主用行政:LAN1\",\n" +
            "            \"id\": \"edge-55\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"53\",\n" +
            "            \"description\": \"core-switch-2:G0/0/5,639会议终端备用行政:LAN1\",\n" +
            "            \"id\": \"edge-56\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"54\",\n" +
            "            \"description\": \"core-switch-1:G0/0/4,B座二层1:LAN1\",\n" +
            "            \"id\": \"edge-57\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"55\",\n" +
            "            \"description\": \"core-switch-2:G0/0/4,B座二层2:LAN1\",\n" +
            "            \"id\": \"edge-58\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"56\",\n" +
            "            \"description\": \"core-switch-2:G0/0/1,19006公司总指挥部1:LAN1\",\n" +
            "            \"id\": \"edge-59\"\n" +
            "        }, {\n" +
            "            \"source\": \"3\",\n" +
            "            \"target\": \"57\",\n" +
            "            \"description\": \"core-switch-2:G0/0/3,19006公司总指挥部2:LAN1\",\n" +
            "            \"id\": \"edge-59\"\n" +
            "        }, {\n" +
            "            \"source\": \"2\",\n" +
            "            \"target\": \"58\",\n" +
            "            \"description\": \"core-switch-1:G0/0/11,应急指挥中心2:LAN1\",\n" +
            "            \"id\": \"edge-60\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"59\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/37,昌平公司应急:LAN1\",\n" +
            "            \"id\": \"edge-61\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"60\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/5,电缆分公司应急:LAN1\",\n" +
            "            \"id\": \"edge-62\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"61\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/13,朝阳公司应急:LAN1\",\n" +
            "            \"id\": \"edge-63\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"62\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/23,大兴公司八层应急:LAN1\",\n" +
            "            \"id\": \"edge-63\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"63\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/3,亦庄公司应急:LAN1\",\n" +
            "            \"id\": \"edge-64\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"64\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/25,客服中心应急:LAN1\",\n" +
            "            \"id\": \"edge-65\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"65\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/21,房山公司应急:LAN1\",\n" +
            "            \"id\": \"edge-67\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"66\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/3,丰台公司应急:LAN1\",\n" +
            "            \"id\": \"edge-68\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"67\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/17,电科院应急:LAN1\",\n" +
            "            \"id\": \"edge-69\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"68\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/19,照明中心应急:LAN1\",\n" +
            "            \"id\": \"edge-70\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"69\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/31,检修公司应急:LAN1\",\n" +
            "            \"id\": \"edge-71\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"70\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/21,工程公司应急:LAN1\",\n" +
            "            \"id\": \"edge-72\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"71\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/21,华商远大应急:LAN1\",\n" +
            "            \"id\": \"edge-73\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"72\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/19,海淀公司应急:LAN1\",\n" +
            "            \"id\": \"edge-74\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"73\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/5,怀柔公司应急:LAN1\",\n" +
            "            \"id\": \"edge-75\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"74\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/7,门头沟新会场行政（应急）:LAN1\",\n" +
            "            \"id\": \"edge-76\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"75\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/1,密云公司应急:LAN1\",\n" +
            "            \"id\": \"edge-77\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"76\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/23,平谷公司应急:LAN1\",\n" +
            "            \"id\": \"edge-78\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"77\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/25,顺义公司应急:LAN1\",\n" +
            "            \"id\": \"edge-79\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"78\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/47,通州公司应急:LAN1\",\n" +
            "            \"id\": \"edge-80\"\n" +
            "        }, {\n" +
            "            \"source\": \"4\",\n" +
            "            \"target\": \"79\",\n" +
            "            \"description\": \"QM-Video-Access-1:G0/0/41,城区公司五层:LAN1\",\n" +
            "            \"id\": \"edge-81\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"80\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/43,昌平19006分指挥部:LAN1\",\n" +
            "            \"id\": \"edge-82\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"81\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/17,国家会议中心现场指挥部:LAN1\",\n" +
            "            \"id\": \"edge-83\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"82\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/3,芦城应急抢修中心:LAN1\",\n" +
            "            \"id\": \"edge-84\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"83\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/47,大兴机场东:LAN1\",\n" +
            "            \"id\": \"edge-85\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"84\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/47,照明中心广场指挥部:LAN1\",\n" +
            "            \"id\": \"edge-86\"\n" +
            "        }, {\n" +
            "            \"source\": \"7\",\n" +
            "            \"target\": \"85\",\n" +
            "            \"description\": \"QM-Video-Access-4:G0/0/27,广场区现场指挥部:LAN1\",\n" +
            "            \"id\": \"edge-87\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"86\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/39,大雁楼备:LAN1\",\n" +
            "            \"id\": \"edge-88\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"87\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/35,大雁楼主:LAN1\",\n" +
            "            \"id\": \"edge-89\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"88\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/11,国际会都现场指挥部:LAN1\",\n" +
            "            \"id\": \"edge-90\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"89\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/1,通州大会议室:LAN1\",\n" +
            "            \"id\": \"edge-91\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"90\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/9,世园会现场指挥部备:LAN1\",\n" +
            "            \"id\": \"edge-92\"\n" +
            "        }, {\n" +
            "            \"source\": \"6\",\n" +
            "            \"target\": \"91\",\n" +
            "            \"description\": \"QM-Video-Access-3:G0/0/5,会城门:LAN1\",\n" +
            "            \"id\": \"edge-93\"\n" +
            "        }, {\n" +
            "            \"source\": \"5\",\n" +
            "            \"target\": \"92\",\n" +
            "            \"description\": \"QM-Video-Access-2:G0/0/33,冬奥会西单办公室:LAN1\",\n" +
            "            \"id\": \"edge-94\"\n" +
            "        }]"+
            "    }\n" +
            "}";

    public Object drawByAll(String deptid) {
        return Json.fromJson(testtemp);
    }
}
